### PR TITLE
github: tag based automated release

### PR DESCRIPTION
**Pull request by cruwaller**
Release is triggered automatically when `rel*_v*` tag is pushed.

### CODE REVIEW

**Review by JyeSmith — APPROVED** [review]

**Comment by JyeSmith** [comment]
Lets get https://github.com/OpenVTx/OpenVTx/pull/41 and https://github.com/OpenVTx/OpenVTx/pull/45 merged then give it a try 😄

**Comment by Asizon** [comment]
@cruwaller there is an error finding platformio:
```
Error: Not a PlatformIO project. `platformio.ini` file has not been found in current working directory (/home/runner/work/OpenVTx/OpenVTx). To initialize new project please use `platformio project init` command
Error: Process completed with exit code 1.
```

**Comment by cruwaller** [comment]
> @cruwaller there is an error finding platformio:
> 
> ```
> Error: Not a PlatformIO project. `platformio.ini` file has not been found in current working directory (/home/runner/work/OpenVTx/OpenVTx). To initialize new project please use `platformio project init` command
> Error: Process completed with exit code 1.
> ```

Oh, nice catch! Thanks a lot, will fix it.

**Comment by cruwaller** [comment]
@JyeSmith this has a bug but I forgot to fix it, sorry!
I will open new a PR to fix it...

**Pull request merged**
